### ISSUE TITLE
Révision Calcul Intégral II

### ISSUE THREAD

**Issue by boisgera** [boisgera/CDIS#121]
#### Modification du périmètre (supression, minoration)

**TODO**

#### Modification du périmètre (ajout, majoration) 

**TODO**

#### Simplifications & changements didactiques 

**TODO**

#### Exercices

  - [ ] ajout exercices embarqués (avec solutions)

  - [ ] adaptation exercices complémentaires (avec solutions)

#### Objectifs 

  - [ ] description initiale (hiérarchisée) des objectifs

  - [ ] hiérarchisation de l'intégralité des contenus
